const TOKEN_MINT = "27TyCz2Y4rFPfURPCPxByEW6AeMfQSNCMFcPmK4fvEA8";
const DATA_URL = "data/transactions.json";
const SOLSCAN_TX = "https://solscan.io/tx/";
const SOLSCAN_TOKEN = "https://solscan.io/token/";

const elements = {
  status: document.querySelector("#networkStatus"),
  tokenName: document.querySelector("#tokenNameValue"),
  supply: document.querySelector("#supplyValue"),
  loaded: document.querySelector("#loadedValue"),
  updated: document.querySelector("#updatedValue"),
  limit: document.querySelector("#limitSelect"),
  refresh: document.querySelector("#refreshButton"),
  prev: document.querySelector("#prevButton"),
  next: document.querySelector("#nextButton"),
  notice: document.querySelector("#notice"),
  body: document.querySelector("#transactionsBody"),
};

let page = 1;
let allRows = [];

function setStatus(text, state = "") {
  elements.status.textContent = text;
  elements.status.className = `status-pill ${state}`.trim();
}

function setNotice(message) {
  elements.notice.hidden = !message;
  elements.notice.textContent = message || "";
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function shortAddress(value) {
  if (!value) return "--";
  return `${value.slice(0, 4)}...${value.slice(-4)}`;
}

function formatDate(seconds) {
  if (!seconds) return "Unknown";
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(seconds * 1000));
}

function formatNumber(value, maximumFractionDigits = 6) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return value || "--";
  return new Intl.NumberFormat(undefined, { maximumFractionDigits }).format(numeric);
}

function renderMeta(payload) {
  const token = payload.token || {};
  const symbol = token.symbol || "Token";
  const name = token.name ? `${token.name} (${symbol})` : symbol;
  elements.tokenName.innerHTML = `<a href="${SOLSCAN_TOKEN}${TOKEN_MINT}" target="_blank" rel="noreferrer">${escapeHtml(name)}</a>`;
  elements.supply.textContent = formatNumber(token.supply, 4);
  elements.updated.textContent = payload.updatedAt
    ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(payload.updatedAt))
    : "--";
}

function renderRows() {
  const limit = Number(elements.limit.value);
  const start = (page - 1) * limit;
  const rows = allRows.slice(start, start + limit);

  elements.loaded.textContent = String(allRows.length);
  elements.prev.disabled = page <= 1;
  elements.next.disabled = start + limit >= allRows.length;

  if (!rows.length) {
    elements.body.innerHTML = '<tr><td colspan="6" class="empty">No transfers found.</td></tr>';
    return;
  }

  elements.body.innerHTML = rows
    .map((row) => {
      const signature = escapeHtml(row.signature);
      const from = escapeHtml(row.from);
      const to = escapeHtml(row.to);
      return `
        <tr>
          <td>
            <div>${formatDate(row.blockTime)}</div>
            <div class="muted">Slot ${escapeHtml(row.slot || "--")}</div>
          </td>
          <td><span class="chip">${escapeHtml(row.type)}</span></td>
          <td class="amount positive">${escapeHtml(row.amountText)}</td>
          <td class="mono" title="${from}">${from ? shortAddress(from) : "--"}</td>
          <td class="mono" title="${to}">${to ? shortAddress(to) : "--"}</td>
          <td class="mono">
            <a href="${SOLSCAN_TX}${signature}" target="_blank" rel="noreferrer">${shortAddress(signature)}</a>
          </td>
        </tr>
      `;
    })
    .join("");
}

async function loadTokenData() {
  setStatus("Loading", "loading");
  setNotice("");
  elements.refresh.disabled = true;
  elements.body.innerHTML = '<tr><td colspan="6" class="empty">Loading cached transfers...</td></tr>';

  try {
    const response = await fetch(`${DATA_URL}?t=${Date.now()}`, {
      headers: { accept: "application/json" },
    });

    if (!response.ok) {
      throw new Error(`Could not load ${DATA_URL} (${response.status})`);
    }

    const payload = await response.json();
    allRows = payload.transactions || [];
    renderMeta(payload);
    renderRows();
    setStatus("Live", "loading");

    if (payload.source) {
      setNotice(`Data source: ${payload.source}. This static page reads cached JSON generated by GitHub Actions, so visitors do not call Solscan directly.`);
    }
  } catch (error) {
    console.error(error);
    setStatus("Error", "error");
    elements.body.innerHTML = '<tr><td colspan="6" class="empty">Could not load cached token transfers.</td></tr>';
    setNotice(`${error.message}. Run the GitHub Actions data updater or open this through a local/static server so data/transactions.json can be fetched.`);
  } finally {
    elements.refresh.disabled = false;
  }
}

elements.refresh.addEventListener("click", () => {
  page = 1;
  loadTokenData();
});
elements.limit.addEventListener("change", () => {
  page = 1;
  renderRows();
});
elements.prev.addEventListener("click", () => {
  page = Math.max(1, page - 1);
  renderRows();
});
elements.next.addEventListener("click", () => {
  page += 1;
  renderRows();
});

loadTokenData();
